#BANDWIDTH API Credentials
BANDWIDTH_USER = 'CHANGE_ME'
BANDWIDTH_TOKEN = 'CHANGE_ME'
BANDWIDTH_SECRET = 'CHANGE_ME'
ROOT_NUMBERS = ["CHANGE_ME","CHANGE_ME"]
ORIGIN_NUMBER = '14703224460'

MINER APIs
MINER_IPS = {0:"CHANGE_ME",1:"CHANGE_ME",2:"CHANGE_ME"}

MAILGUN_API_URL = "CHANGE_ME"

#ALARM Settings
ALARM_TEMP = 90
MAX_TEMP = 95
INTERVAL = 120 #Seconds